baseURL = 'http://localhost/'
canonifyURLs = false
relativeURLs = false
languageCode = "en"
defaultContentLanguage = "en"
title = 'Google Applied ML'

themesdir = "themes"
theme = "hugo-theme-relearn"

[params]
  editURL = "https://github.com/rmcguinness/applied-ai/blob/content/"
  description = "Google Applied GenAI"
  author = "Google"
  showVisitedLinks = true
  collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  titleSeparator = "::"
  themeVariant = [ "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]
  disableSeoHiddenPages = true
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  additionalContentLanguage = [ "en" ]

[outputs]
  # add JSON to the home to support lunr search; This is a mandatory setting
  # for the search functionality
  # add PRINT to home, section and page to activate the feature to print whole
  # chapters
  home = ["HTML", "RSS", "PRINT", "JSON"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.highlight]
    guessSyntax = false
    noClasses = false
    # style = "tango"
  [markup.goldmark.renderer]
    unsafe = true

[server]
  [[server.headers]]
    for = "**.html"
    [server.headers.values]
       X-UA-Compatible = "IE=edge"
